 const words = [	
	{
		"0": "That",
		"1": "My",
		"2": "Your",
		"3": "As for",
		"4": "His",
		"5": "Each",
		"6": "New",
		"7": "Her",
		"8": "And",
	},
	{
		"0": "autumn",
		"1": "honest",
		"2": "conscious",
		"3": "deep",
		"4": "every",
		"5": "friendly",
		"6": "gorgeous",
		"7": "guilty",
		"8": "lonely",
	},
	{
		"0": "night",
		"1": "heart",
		"2": "face",
		"3": "feeling",
		"4": "thought",
		"5": "sight",
		"6": "mind",
		"7": "splendor",
		"8": "dream",
	},
	{
		"0": "was",
		"1": "seemed",
		"2": "looked",
		"3": "has painted",
		"4": "belonged",
		"5": "has",
		"6": "was",
		"7": "got",
		"8": "kept",
	},
	{
		"0": "dark",
		"1": "plane",
		"2": "cold",
		"3": "clean",
		"4": "smart",
		"5": "unknown",
		"6": "heavy",
		"7": "drown",
		"8": "hard",
	},
	{
		"0": "and tender",
		"1": "in that november",
		"2": "for my contender",
		"3": "tight and slender",
		"4": "bender",
		"5": "temper",
		"6": "frequenter",
		"7": "by trembler",
		"8": "to render",
	}
];

export default words